apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s 
    scrape_configs:
      - job_name: "event-processor"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["event-processor-service.default.svc.cluster.local:8000"]
    rule_files:
      - "/etc/prometheus/alerts.yml"
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - "alertmanager-service.default.svc.cluster.local:9093"
  alerts.yml: |
    groups:
      - name: event_alerts
        rules:
          - alert: HighEventRate
            expr: events_processed_total > 100
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Zu viele Events verarbeitet"
              description: "Mehr als 100 Events wurden in kurzer Zeit verarbeitet."
          
          - alert: NewIoTDevice
            expr: increase(unique_devices_total[1m]) > 0
            for: 1m
            labels:
              severity: info
            annotations:
              summary: "Neues IoT-Gerät entdeckt"
              description: "Ein neues IoT-Gerät wurde erkannt."
          
          - alert: HighWeldingTemperature  
            expr: max_over_time(welding_temperature[5m]) > 1500
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Gefährlich hohe Schweißtemperatur!"
              description: "Die Schweißtemperatur ist über 1500°C gestiegen."